import { weapon, ammo } from "../../helpers.js";

export const WEAPON_EFFECTS_RANGED = {
  "Arc":weapon("Arc projetant des flèches par tension de corde.",["tir à distance","tir précis"],[],{weaponType:"ranged",ammunition:ammo("flèche",{physical:true,reusableByDefault:false}),fireMode:"tir unitaire"}),
  "Arbalète":weapon("Arbalète mécanique projetant des carreaux.",["tir à distance","mise en joue","tir précis","rechargement"],["Rechargement plus lent qu'un arc entre deux tirs préparés."],{weaponType:"ranged",ammunition:ammo("carreau",{physical:true,reusableByDefault:false}),fireMode:"tir unitaire"}),
  "Pistolet":weapon("Arme à feu compacte.",["tir rapide","combat rapproché à moyenne distance"],[],{weaponType:"ranged",ammunition:ammo("balle / cartouche",{physical:true}),fireMode:"tir balistique"}),
  "Fusil":weapon("Arme à feu longue polyvalente.",["tir à distance","précision","engagement à moyenne ou longue portée"],[],{weaponType:"ranged",ammunition:ammo("balle / cartouche",{physical:true}),fireMode:"tir balistique"}),
  "Fusil de précision":weapon("Arme à feu optimisée pour la précision à très longue portée.",["tir précis","engagement à très longue portée"],["Moins adaptée au combat très rapproché."],{weaponType:"ranged",ammunition:ammo("balle / cartouche",{physical:true}),fireMode:"tir balistique précis"}),
  "Fusil à pompe":weapon("Arme à feu efficace surtout à courte ou moyenne portée.",["tir puissant","dispersion ou projectile unique selon la cartouche"],["Ne pas inventer de munition spéciale."],{weaponType:"ranged",ammunition:ammo("cartouche de fusil à pompe",{physical:true,possibleLoads:["projectiles multiples","slug"]}),fireMode:"tir balistique"}),
  "Mitrailleuse":weapon("Arme à feu automatique conçue pour le tir soutenu.",["rafale","tir soutenu","suppression"],["Plus lourde et moins maniable qu'une arme légère."],{weaponType:"ranged",ammunition:ammo("balles / cartouches",{physical:true}),fireMode:"automatique"}),
  "Lance-roquettes":weapon("Lanceur projetant des roquettes explosives.",["tir explosif","attaque de zone"],["Faible cadence.","Usage dangereux à très courte distance."],{weaponType:"ranged",ammunition:ammo("roquette explosive",{physical:true,explosive:true}),fireMode:"tir unitaire"}),
  "Canon runique portatif":weapon("Arme lourde à distance utilisant des runes pour produire et projeter une décharge énergétique.",["tir runique à distance"],["Les runes ne créent pas d'effets arbitraires supplémentaires."],{weaponType:"ranged",ammunition:null,projectile:{type:"décharge d'énergie runique",physical:false}}),
  "Fusil à portails":weapon("Arme à distance dont l'émission crée des portails ponctuels servant à modifier une ligne de tir ou un passage d'attaque.",["création de portails liés au tir","redirection de trajectoire"],["Ne confère pas librement le pouvoir Espace ou Téléportation.","Les portails ne produisent pas à eux seuls une conséquence majeure non décidée par le moteur."],{weaponType:"ranged",ammunition:null,projectile:{type:"émission énergétique de portail",physical:false}})
};
