export const METAMORPHOSIS_FORMS=[
  "Loup",
  "Renard",
  "Ours",
  "Lion",
  "Tigre",
  "Guépard",
  "Panthère",
  "Hyène",
  "Sanglier",
  "Taureau",
  "Cerf",
  "Cheval",
  "Gorille",
  "Éléphant",
  "Rhinocéros",
  "Crocodile",
  "Serpent",
  "Aigle",
  "Faucon",
  "Corbeau",
  "Hibou",
  "Requin",
  "Orque",
  "Pieuvre",
  "Araignée",
  "Scorpion",
  "Mante religieuse",
  "T. rex",
  "Vélociraptor",
  "Tricératops",
  "Ankylosaure",
  "Spinosaurus",
  "Ptéranodon",
  "Smilodon",
  "Mammouth",
  "Mégalodon",
  "Griffon",
  "Hippogriffe",
  "Phénix",
  "Hydre",
  "Manticore",
  "Chimère",
  "Basilic",
  "Cockatrice",
  "Pégase",
  "Licorne",
  "Cerbère",
  "Minotaure",
  "Sphinx",
  "Kraken",
  "Wyverne",
  "Roc",
  "Kitsune",
  "Kirin",
  "Naga",
  "Oni",
  "Wendigo",
  "Gargouille",
  "Golem",
  "Ent",
  "Slime",
  "Mimique",
  "Ver géant",
  "Chauve-souris géante",
  "Araignée géante",
  "Loup géant",
  "Serpent géant",
  "Dragon",
  "Elfe",
  "Orc",
  "Nain",
  "Gobelin",
  "Fée",
  "Neoxus",
  "Homme-bête",
  "Ange",
  "Démon",
  "Drakéon",
  "Liche",
  "Élémentaire de feu",
  "Élémentaire d’eau",
  "Élémentaire de terre",
  "Élémentaire d’air",
  "Élémentaire de glace",
  "Élémentaire de foudre",
  "Élémentaire de lumière",
  "Élémentaire d’ombre"
];
