/* ========================= HGT COMBAT ENGINE V1 =========================
   The character sheet remains the canonical source. Combat profiles are
   compiled on demand; resolved battles keep a snapshot for historical use.
   ====================================================================== */
export const HGT_COMBAT_ENGINE_VERSION='combat-v1.0.0';
export const HGT_COMBAT_RULES_VERSION='rules-107-v1';
export const HGT_COMBAT_CONFIG={interactionCapPoints:15,environmentCapPoints:10,minProbability:.05,maxProbability:.95,diminishing:[1,.75,.5,.25]};
export const HGT_SEASONS=['Printemps','Été','Automne','Hiver'];
export const HGT_REGION_CLIMATE={
 Aetherys:{temps:[11,17,9,3],weather:[['Clair',25],['Nuageux',25],['Brume',20],['Bruine',12],['Pluie',10],['Forte pluie',5],['Orage',3]],humidity:55,wind:30},
 Thoryndra:{temps:[5,11,4,-3],weather:[['Nuageux',15],['Brume',8],['Bruine',7],['Pluie',20],['Forte pluie',18],['Orage',17],['Violent orage',10],['Grêle',5]],humidity:72,wind:48},
 Liorael:{temps:[14,21,12,7],weather:[['Clair',20],['Nuageux',25],['Brume',15],['Bruine',15],['Pluie',18],['Forte pluie',5],['Orage',2]],humidity:74,wind:18},
 Caelorn:{temps:[13,20,11,5],weather:[['Clair',30],['Partiellement nuageux',20],['Nuageux',20],['Bruine',8],['Pluie',12],['Averse',7],['Orage',3]],humidity:55,wind:35},
 Sylvaeryn:{temps:[14,22,13,7],weather:[['Clair',10],['Nuageux',20],['Brume',20],['Bruine',18],['Pluie',20],['Forte pluie',9],['Orage',3]],humidity:82,wind:12},
 Kharadryn:{temps:[4,11,2,-9],weather:[['Clair froid',25],['Nuageux',20],['Brouillard',10],['Pluie',10],['Neige légère',15],['Neige',10],['Forte neige',6],['Blizzard',4]],humidity:48,wind:42},
 Avelorn:{temps:[14,25,13,4],weather:[['Clair',30],['Partiellement nuageux',20],['Nuageux',18],['Bruine',8],['Pluie',12],['Forte pluie',5],['Orage',7]],humidity:55,wind:20},
 Drakhenor:{temps:[24,35,25,17],weather:[['Clair',48],['Partiellement nuageux',17],['Voile poussiéreux',18],['Nuageux',7],['Pluie',4],['Orage sec',3],['Tempête de poussière',3]],humidity:20,wind:26},
 Maelora:{temps:[26,30,27,23],weather:[['Éclaircies',8],['Nuageux',17],['Brume',15],['Bruine',10],['Pluie',20],['Forte pluie',15],['Pluie torrentielle',8],['Orage',7]],humidity:91,wind:18},
 Iskarya:{temps:[-15,-4,-13,-26],weather:[['Clair froid',22],['Nuageux',18],['Brouillard glacé',10],['Neige légère',18],['Neige',15],['Forte neige',10],['Blizzard',7]],humidity:35,wind:45},
 Nexara:{temps:[17,27,17,9],weather:[['Clair',25],['Partiellement nuageux',20],['Nuageux',15],['Brume',12],['Pluie',10],['Orage',5],['Brume énergétique',8],['Particules énergétiques',5]],humidity:50,wind:18},
 Kaelora:{temps:[27,31,28,24],weather:[['Clair',25],['Partiellement nuageux',15],['Nuageux tropical',12],['Averse',15],['Forte pluie',12],['Pluie torrentielle',8],['Orage tropical',8],['Grain violent',5]],humidity:86,wind:25},
 Vaerunn:{temps:[13,20,12,6],weather:[['Éclaircies',10],['Nuageux',15],['Bruine',10],['Pluie',20],['Forte pluie',15],['Orage',12],['Violent orage',10],['Tempête',8]],humidity:88,wind:48},
 "Mor'Khal":{temps:[25,25,25,25],weather:[['Air sec',45],['Air poussiéreux',25],['Brume minérale',10],['Courants souterrains',15],['Nuage de poussière',5]],humidity:22,wind:12,underground:true},
 Kythera:{temps:[11,11,11,11],weather:[['Air cristallin',45],['Brume légère',20],['Poussière cristalline',15],['Courants souterrains',15],['Nuage cristallin dense',5]],humidity:52,wind:10,underground:true},
 Lumerys:{temps:[18,18,18,18],weather:[['Air humide',25],['Brume bioluminescente',25],['Brume dense',15],['Spores légères',20],['Nuage de spores',10],['Condensation',5]],humidity:92,wind:6,underground:true},
 Varkhoryn:{temps:[42,42,42,42],weather:[['Air brûlant',20],['Fumées volcaniques',25],['Cendres légères',25],['Cendres denses',15],['Émanations brûlantes',10],['Activité volcanique intense',5]],humidity:15,wind:18,underground:true},
 Naeroth:{temps:[12,12,12,12],weather:[['Air humide calme',20],['Brume marine',20],['Embruns',20],['Brume dense',10],['Vent marin souterrain',15],['Orage souterrain',10],['Violent orage',5]],humidity:95,wind:28,underground:true}
};
export function hgtNorm(v){return String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()}
export function hgtWeighted(items){let total=items.reduce((n,x)=>n+Math.max(0,Number(x[1])||0),0),r=Math.random()*total;for(const x of items){r-=Math.max(0,Number(x[1])||0);if(r<=0)return x[0]}return items[items.length-1]?.[0]}
export function hgtSeasonForTournament(t){if(t?.seasonName&&HGT_SEASONS.includes(t.seasonName))return t.seasonName;const n=Math.max(1,Number(t?.season)||1);return HGT_SEASONS[(n-1)%4]}
export function hgtTime(){const periods=[['Nuit profonde',0,4],['Aube',5,6],['Matin',7,10],['Midi',11,13],['Après-midi',14,17],['Crépuscule',18,19],['Soirée',20,23]],p=periods[Math.floor(Math.random()*periods.length)],h=p[1]+Math.floor(Math.random()*(p[2]-p[1]+1)),m=Math.floor(Math.random()*60);return {period:p[0],hour:`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}`,hourValue:h}}
export function hgtGenerateConditions(ctx,t){
 const climate=HGT_REGION_CLIMATE[ctx.region]||HGT_REGION_CLIMATE.Avelorn,season=hgtSeasonForTournament(t),si=HGT_SEASONS.indexOf(season),time=hgtTime(),weather=hgtWeighted(climate.weather),wn=hgtNorm(weather);
 const hourAdj=time.hourValue<5?-4:time.hourValue<7?-3:time.hourValue<11?-1:time.hourValue<14?2:time.hourValue<18?3:time.hourValue<20?0:-2;
 let temp=(climate.temps[si]??15)+(Math.random()*8-4)+(climate.underground?0:hourAdj);if(/neige|blizzard|glace/.test(wn))temp=Math.min(temp,1);if(/pluie|averse|orage/.test(wn))temp-=1.5;if(ctx.terrain==='Montagne')temp-=4;if(ctx.region==='Varkhoryn')temp=Math.max(30,temp);temp=Math.round(temp*10)/10;
 let humidity=Math.max(5,Math.min(100,climate.humidity+(/pluie|averse|brume|brouillard|embrun|spore/.test(wn)?12:0)+Math.round(Math.random()*12-6)));
 let wind=Math.max(0,Math.round(climate.wind+Math.random()*20-10+(/tempete|violent|blizzard|orage/.test(wn)?25:0))),gusts=Math.round(wind*(1.15+Math.random()*.35));
 const windIntensity=wind<5?'Calme':wind<=15?'Faible':wind<=30?'Modéré':wind<=50?'Fort':wind<=75?'Violent':'Tempétueux';
 let visibility=/blizzard|tempete de poussiere|brume dense|cendres denses|pluie torrentielle/.test(wn)?20:/brume|brouillard|forte pluie|neige|spore|poussiere|embrun/.test(wn)?70:/pluie|nuageux|cendre/.test(wn)?180:600;
 if(ctx.terrain==='Forêt dense')visibility=Math.min(visibility,90);if(ctx.terrain==='Caverne')visibility=Math.min(visibility,60);
 const visLevel=visibility<5?'Quasi nulle':visibility<25?'Très faible':visibility<75?'Faible':visibility<200?'Moyenne':visibility<500?'Bonne':'Excellente';
 const dark=climate.underground||time.hourValue<6||time.hourValue>=20,lighting={level:dark?'Faible':(/orage|brume dense|blizzard/.test(wn)?'Modérée':'Claire'),source:climate.underground?(ctx.region==='Lumerys'?'Bioluminescence':ctx.region==='Kythera'?'Cristaux':ctx.region==='Varkhoryn'?'Magma':'Lumières souterraines'):'Lumière naturelle'};
 const wet=/pluie|averse|bruine|orage|embrun/.test(wn)||ctx.terrain==='Marais'||ctx.terrain==='Zone aquatique',icy=/neige|blizzard|glace/.test(wn)||temp<=-5,dust=/poussiere|cendre/.test(wn)||ctx.terrain==='Désert';
 const ground={base:ctx.terrain==='Désert'?'sable':ctx.terrain==='Zone aquatique'?'eau':ctx.terrain==='Ville'||ctx.terrain==='Ruines'?'pierre':'terre',moisture:ctx.terrain==='Zone aquatique'?'inondé':wet?'détrempé':'sec',traction:icy||wet?'glissant':dust?'médiocre':'normale',stability:['Ruines','Montagne','Marais'].includes(ctx.terrain)?'irrégulier':'stable',cover:[...(wet?['eau/boue']:[]),...(icy?['neige/glace']:[]),...(dust?['poussière/cendres']:[])]};
 return {version:1,season,time:{period:time.period,hour:time.hour},weather:{type:weather,intensity:/violent|torrentielle|blizzard|tempete|intense/.test(wn)?'forte':/forte|orage/.test(wn)?'importante':'normale'},temperatureC:temp,wind:{intensity:windIntensity,speedKmh:wind,gustsKmh:gusts,direction:['N','NE','E','SE','S','SO','O','NO'][Math.floor(Math.random()*8)]},visibility:{level:visLevel,approximateRangeM:visibility},ground,lighting,humidity,air:{clarity:visibility<75?'trouble':'normale',particles:ground.cover.slice()},atmosphere:weather,environmentalEvent:null};
}
function hgtText(c,{excludeWeakness=false}={}){const seen=new WeakSet();return hgtNorm(JSON.stringify(c,(k,v)=>{if(['logs','imageGeneration','genealogy','relationships'].includes(k)||(excludeWeakness&&['weakness','gravity'].includes(k)))return undefined;if(v&&typeof v==='object'){if(seen.has(v))return undefined;seen.add(v)}return v}))}
function hgtWeakness(c){const raw=String(c?.weakness||''),m=raw.match(/(.+?)(?:\s*[—-]\s*(\d+)\s*\/\s*10)?$/);return {name:(m?.[1]||raw).trim(),severity:Number(m?.[2])||0}}
export function hgtCompileCombatProfile(c,id=''){
 c=c||{};const text=hgtText(c,{excludeWeakness:true}),weak=hgtWeakness(c),powers=(c.powers||[]).map(p=>({name:p.name||'',mastery:Number(p.mastery)||0,source:'power'})),weapons=(c.weapons||[]).map(w=>({name:w.name||'',mastery:Number(w.mastery)||0,enchantments:[...(w.ench||w.enchantments||[])],source:'weapon'}));
 const tags=new Set();const add=(tag,re)=>{if(re.test(text))tags.add(tag)};
 add('fire',/feu|flamme|incend|volcani|brul/);add('water',/\beau\b|aquati|marin|kraken|leviathan/);add('ice',/glace|glacial|neige|givre|froid/);add('electricity',/foudre|electri|eclair/);add('air',/\bair\b|vent|rafale/);add('earth',/\bterre\b|roche|mineral/);add('nature',/nature|veget|plante|spore|champignon/);add('light',/lumiere|solaire|celeste/);add('darkness',/tenebre|ombre/);add('poison',/poison|tox|venin/);add('blood',/sang/);add('magnetism',/magnet/);add('sound',/sonique|\bson\b|cri|silence absolu/);add('explosion',/explosion|explosi/);add('telekinesis',/telekines/);add('telepathy',/telepath/);add('illusion',/illusion/);add('invisibility',/invisib|camouflage optique/);add('teleport',/teleport|portail/);add('gravity',/gravite|gravitation/);add('time',/temps|temporel|time slasher/);add('space',/espace|spatial|dimension/);add('absorption',/absorption/);add('copy',/\bcopie\b|copier/);add('nullification',/annulation|anti-magie|zone sans magie/);add('regeneration',/regener/);add('barrier',/barriere|bouclier/);add('flight',/\bvol\b|ailes|aviaire|pegase/);add('thermalVision',/vision thermique|detection thermique/);add('altSense',/echoloc|vision surnaturelle|scanner biologique|sens de piste|perception/);add('adaptation',/adaptation|memorise les attaques|mémorise les attaques/);add('storage',/stockage|stocke une attaque/);add('transfer',/vol de mouvement|vol d.inertie|transfert|echange de blessures|échange de blessures/);add('zone',/zone sans magie|zone de protection|stase/);add('learning',/lecture du combat|analyse tactique|memoire parfaite|mémoire parfaite/);add('controlledUnknown',/effet impossible|extra totalement absurde|capacite biologique inconnue|capacité biologique inconnue|logique ne peut expliquer/);
 return {id,name:c.name||id,race:c.race||'',arch:c.arch||'',job:c.job||'',stats:{...(c.stats||{})},powers,weapons,weakness:weak,blessings:[...(c.blessings||[])],curses:[...(c.curses||[])],extraDetail:[...(c.extraDetail||[])],transformation:c.transformation||null,awakening:c.awakening||null,chi:c.chi||null,martial:martialCombatData(c),tags:[...tags],sourceFingerprint:hgtFingerprint(c),rulesVersion:HGT_COMBAT_RULES_VERSION};
}
function hgtFingerprint(c){const x=JSON.stringify(c,(k,v)=>['logs','imageGeneration','genealogy','relationships'].includes(k)?undefined:v);let h=2166136261;for(let i=0;i<x.length;i++){h^=x.charCodeAt(i);h=Math.imul(h,16777619)}return (h>>>0).toString(36)}
function hgtKnowledgeScore(k){return k==='Bonne connaissance de l’adversaire'?1:k==='Informations partielles'?.5:0}
function hgtBuildInteractions(a,b,ctx,conditions){
 const out=[],push=(actor,target,key,impact,category,reason,environment=false)=>{impact=Math.max(0,Math.min(4,Number(impact)||0));if(!impact)return;out.push({actor,target,causalKey:key,impact,category,reason,environment})},ta=new Set(a.tags),tb=new Set(b.tags),wA=hgtNorm(a.weakness.name),wB=hgtNorm(b.weakness.name),wet=conditions.ground.moisture!=='sec',lowVis=conditions.visibility.approximateRangeM<75,strongWind=conditions.wind.speedKmh>50,icy=conditions.ground.cover.some(x=>/glace|neige/.test(x));
 const exposeWeak=(actor,target,ts,w,key)=>{if(!w.name||!w.severity)return;const n=hgtNorm(w.name);const pairs=[['electricity',/electri|foudre|eclair/],['fire',/feu|chaleur|brul/],['ice',/glace|froid/],['water',/eau|aquati/],['sound',/son|bruit|applaud/],['nature',/champignon|spore|veget|nature/],['magnetism',/magnet/],['light',/lumiere/],['darkness',/tenebre|ombre/],['poison',/poison|tox|venin/],['time',/temps|temporel/],['space',/espace|spatial|dimension/],['explosion',/explosion/]];for(const [tag,re] of pairs)if(ts.has(tag)&&re.test(n)){push(actor,target,`${actor}:${tag}>${target}:weakness`,Math.min(4,Math.max(1,w.severity/2.5)),'vulnerability',`Faiblesse ${w.name} exposée par ${tag}`);break}};
 exposeWeak('A','B',ta,b.weakness,'B');exposeWeak('B','A',tb,a.weakness,'A');
 if(wet){if(ta.has('electricity'))push('A','B','A:electricity:wet',2.5,'environment','La conductivité du terrain humide favorise la Foudre',true);if(tb.has('electricity'))push('B','A','B:electricity:wet',2.5,'environment','La conductivité du terrain humide favorise la Foudre',true);if(ta.has('fire'))push('B','A','A:fire:wet-penalty',1.5,'environment','L’humidité gêne certaines utilisations du Feu',true);if(tb.has('fire'))push('A','B','B:fire:wet-penalty',1.5,'environment','L’humidité gêne certaines utilisations du Feu',true)}
 if(lowVis){if(ta.has('thermalVision')||ta.has('altSense'))push('A','B','A:senses:lowvis',2,'environment','Perception alternative dans une visibilité réduite',true);if(tb.has('thermalVision')||tb.has('altSense'))push('B','A','B:senses:lowvis',2,'environment','Perception alternative dans une visibilité réduite',true);if(ta.has('invisibility')&&!tb.has('altSense')&&!tb.has('thermalVision'))push('A','B','A:invisibility:detection',2.5,'matchup','Invisibilité difficile à détecter');if(tb.has('invisibility')&&!ta.has('altSense')&&!ta.has('thermalVision'))push('B','A','B:invisibility:detection',2.5,'matchup','Invisibilité difficile à détecter')}
 if(strongWind){if(ta.has('flight'))push('B','A','A:flight:wind',2,'environment','Vent violent défavorable au vol',true);if(tb.has('flight'))push('A','B','B:flight:wind',2,'environment','Vent violent défavorable au vol',true)}
 if(icy){const aAdapt=/glace|glacial|iskarya|resistance environnementale/.test(hgtText(a)),bAdapt=/glace|glacial|iskarya|resistance environnementale/.test(hgtText(b));if(aAdapt&&!bAdapt)push('A','B','A:ice-adaptation',1.5,'environment','Meilleure adaptation au terrain gelé',true);if(bAdapt&&!aAdapt)push('B','A','B:ice-adaptation',1.5,'environment','Meilleure adaptation au terrain gelé',true)}
 if(ctx.distance>=25){if(ta.has('teleport'))push('A','B','A:teleport:distance',2.5,'matchup','Téléportation permettant de casser la distance');if(tb.has('teleport'))push('B','A','B:teleport:distance',2.5,'matchup','Téléportation permettant de casser la distance')}
 if(ta.has('regeneration')&&tb.has('nullification'))push('B','A','B:nullify>A:regen',2.5,'counter','Neutralisation susceptible de réduire la régénération');if(tb.has('regeneration')&&ta.has('nullification'))push('A','B','A:nullify>B:regen',2.5,'counter','Neutralisation susceptible de réduire la régénération');
 return hgtFuseInteractions(out)
}
function hgtFuseInteractions(items){const arr=[...items],drop=new Set();for(let i=0;i<arr.length;i++){const x=arr[i];if(!/:electricity:wet$/.test(x.causalKey))continue;const j=arr.findIndex((y,n)=>n!==i&&y.actor===x.actor&&y.target===x.target&&/:electricity>.*:weakness$/.test(y.causalKey));if(j>=0){arr[j]={...arr[j],impact:Math.min(4,Math.max(arr[j].impact,arr[j].impact+x.impact*.25)),environment:true,reason:`${arr[j].reason} dans un environnement conducteur`,causes:[arr[j].reason,x.reason]};drop.add(i)}}const map=new Map();for(let i=0;i<arr.length;i++){if(drop.has(i))continue;const x=arr[i],family=x.causalKey.replace(/:wet|-penalty/g,''),k=`${x.actor}>${x.target}:${family}`,old=map.get(k);if(!old||x.impact>old.impact)map.set(k,{...x,causes:old?[...(old.causes||[old.reason]),x.reason]:(x.causes||[x.reason])})}return [...map.values()]}
function hgtInteractionScore(items,actor,environmentOnly=false){const arr=items.filter(x=>x.actor===actor&&(!environmentOnly||x.environment)).sort((a,b)=>b.impact-a.impact);return arr.reduce((sum,x,i)=>sum+x.impact*(HGT_COMBAT_CONFIG.diminishing[Math.min(i,3)]),0)}
export function hgtCombatAnalysis(a,b,ctx,conditions,baseProbA){const interactions=hgtBuildInteractions(a,b,ctx,conditions),sa=hgtInteractionScore(interactions,'A'),sb=hgtInteractionScore(interactions,'B'),ea=hgtInteractionScore(interactions,'A',true),eb=hgtInteractionScore(interactions,'B',true),env=Math.max(-HGT_COMBAT_CONFIG.environmentCapPoints,Math.min(HGT_COMBAT_CONFIG.environmentCapPoints,ea-eb)),raw=sa-sb,modifier=Math.max(-HGT_COMBAT_CONFIG.interactionCapPoints,Math.min(HGT_COMBAT_CONFIG.interactionCapPoints,raw)),applied=Math.abs(env)>Math.abs(modifier)?env:modifier,final=Math.max(HGT_COMBAT_CONFIG.minProbability,Math.min(HGT_COMBAT_CONFIG.maxProbability,baseProbA+applied/100));return {version:1,baseProbability:{a:+baseProbA.toFixed(4),b:+(1-baseProbA).toFixed(4)},interactions,rawInteractionScores:{a:+sa.toFixed(2),b:+sb.toFixed(2)},environmentScores:{a:+ea.toFixed(2),b:+eb.toFixed(2)},relativeModifierPoints:+applied.toFixed(2),finalProbability:{a:+final.toFixed(4),b:+(1-final).toFixed(4)}}}
export function hgtSnapshot(profile){return {id:profile.id,name:profile.name,sourceFingerprint:profile.sourceFingerprint,rulesVersion:profile.rulesVersion,tags:[...profile.tags],weakness:{...profile.weakness}}}
export function hgtNarrativeFromBattle(battle,a,b){const winner=battle.winner===battle.a?a:b,loser=battle.winner===battle.a?b:a,ints=(battle.analysis?.interactions||[]).slice().sort((x,y)=>y.impact-x.impact),key=ints[0],c=battle.conditions||{},weather=c.weather?.type||'conditions changeantes';const pa=battle.analysis?.finalProbability?.a??battle.probA??.5,expected=pa>=.5?battle.a:b,upset=expected!==battle.winner;const opening=`À ${c.time?.hour||'une heure indéterminée'}, ${a.name||battle.a} et ${b.name||battle.b} se font face sur ${String(battle.terrain||'le terrain').toLowerCase()}, sous ${String(weather).toLowerCase()}. La distance initiale est de ${battle.distance??'plusieurs'} mètres.`;const middle=key?`Le combat bascule lorsque ${key.reason.toLowerCase()}. Les deux adversaires adaptent leur rythme, sans que cet avantage suffise à lui seul à décider de l’issue.`:`Aucun facteur contextuel ne domine nettement l’affrontement : les échanges reposent surtout sur les qualités propres des deux combattants.`;const turn=upset?`${winner.name||battle.winner}, pourtant désavantagé avant le tirage final, exploite une ouverture décisive et renverse progressivement le rapport de force.`:`${winner.name||battle.winner} transforme progressivement son avantage en ouverture décisive.`;const end=battle.death===battle.loser?`${loser.name||battle.loser} reçoit finalement une blessure mortelle. ${winner.name||battle.winner} demeure seul en état de poursuivre le tournoi.`:`Après le dernier échange, ${loser.name||battle.loser} n’est plus en mesure de poursuivre. ${winner.name||battle.winner} remporte le combat.`;return {version:1,chronicle:[opening,middle,turn,end].join('\n\n'),closingLine:`🏆 ${winner.name||battle.winner} remporte l’affrontement.`,direction:{tone:'cinematic_dark_fantasy',estimatedDurationSec:upset?120:Math.abs(pa-.5)>.3?45:90,intensity:'high',pacing:upset?'progressive':'dynamic'},sequences:[],generatedAt:new Date().toISOString(),generator:'deterministic-v1'}}
export function hgtPrepareBattleContext(ctx,t,a,b,idA,idB,baseProbA){const conditions=hgtGenerateConditions(ctx,t),pa=hgtCompileCombatProfile(a,idA),pb=hgtCompileCombatProfile(b,idB),analysis=hgtCombatAnalysis(pa,pb,ctx,conditions,baseProbA);return {conditions,profiles:{a:pa,b:pb},analysis}}

/* ======================= END HGT COMBAT ENGINE V1 ======================= */
